name: division2 bot

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pip install requests

      - run: python script.py

      - name: Save state
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add last.json
          git commit -m "update" || echo "no change"
          git push
