name: division2 bot

on:
  schedule:
    - cron: "48 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # ←ここだけ変更

      - run: pip install requests

      - run: python script.py
